### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by wolfe3d** [wolfe3d/sodata#7]
Need to figure out why the google token is lost.

Fatal error: Uncaught Google\Service\Exception: { "error": { "code": 401, "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "errors": [ { "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.", "domain": "global", "reason": "unauthorized" } ], "status": "UNAUTHENTICATED" } } in D:\Ampps\www\sodata\google-api-php-client\src\Http\REST.php:128 Stack trace: #0 D:\Ampps\www\sodata\google-api-php-client\src\Http\REST.php(103): Google\Http\REST::decodeHttpResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request), 'Google_Service_...') #1 [internal function]: Google\Http\REST::doExecute(Object(GuzzleHttp\C in D:\Ampps\www\sodata\google-api-php-client\src\Http\REST.php on line 128

**Comment by wolfe3d** [comment]
In logs: [Sun May 02 17:51:22.037737 2021] [php7:error] [pid 23874] [client 76.240.25.24:56977] PHP Fatal error:  Uncaught Google\\Service\\Exception: {\n  "error": {\n    "code": 401,\n    "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n    "errors": [\n      {\n        "message": "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",\n        "domain": "global",\n        "reason": "unauthorized"\n      }\n    ],\n    "status": "UNAUTHENTICATED"\n  }\n}\n in /var/www/scienceolympiad/google-api-php-client/src/Http/REST.php:128\nStack trace:\n#0 /var/www/scienceolympiad/google-api-php-client/src/Http/REST.php(103): Google\\Http\\REST::decodeHttpResponse()\n#1 [internal function]: Google\\Http\\REST::doExecute()\n#2 /var/www/scienceolympiad/google-api-php-client/src/Task/Runner.php(182): call_user_func_arr in /var/www/scienceolympiad/google-api-php-client/src/Http/REST.php on line 128
